[recent]
title = "뉴스타파 ─ 뉴스"
url = "http://newstapa.org/recent"
entrySelector = "article.article"
titleSelector = "h6.font-weight-bold"
linkSelector = "h6.font-weight-bold a"
contentSelector = "h6.font-weight-bold a"
dateSelector = "p.float-right.mt-2.date"
dateFormat = "yyyy.MM.dd"
imageSelector = "figure.article-image img.d-block.w-100"
waitUntil = "networkidle"

[news_public]
title = "뉴스타파 ─ 뉴스 ─ 공직감시"
url = "http://newstapa.org/category/%EA%B3%B5%EC%A7%81%EA%B0%90%EC%8B%9C"
entrySelector = "article.article"
titleSelector = "h6.font-weight-bold"
linkSelector = "h6.font-weight-bold a"
contentSelector = "h6.font-weight-bold a"
dateSelector = "p.float-right.mt-2.date"
dateFormat = "yyyy.MM.dd"
imageSelector = "figure.article-image img.d-block.w-100"
waitUntil = "networkidle"

[news_justice]
title = "뉴스타파 ─ 뉴스 ─ 사법정의"
url = "http://newstapa.org/category/%EC%82%AC%EB%B2%95%EC%A0%95%EC%9D%98"
entrySelector = "article.article"
titleSelector = "h6.font-weight-bold"
linkSelector = "h6.font-weight-bold a"
contentSelector = "h6.font-weight-bold a"
dateSelector = "p.float-right.mt-2.date"
dateFormat = "yyyy.MM.dd"
imageSelector = "figure.article-image img.d-block.w-100"
waitUntil = "networkidle"

[news_budget]
title = "뉴스타파 ─ 뉴스 ─ 예산감시"
url = "http://newstapa.org/category/%EC%98%88%EC%82%B0%EA%B0%90%EC%8B%9C"
entrySelector = "article.article"
titleSelector = "h6.font-weight-bold"
linkSelector = "h6.font-weight-bold a"
contentSelector = "h6.font-weight-bold a"
dateSelector = "p.float-right.mt-2.date"
dateFormat = "yyyy.MM.dd"
imageSelector = "figure.article-image img.d-block.w-100"
waitUntil = "networkidle"

[news_chaebol]
title = "뉴스타파 ─ 뉴스 ─ 재벌"
url = "http://newstapa.org/category/%EC%9E%AC%EB%B2%8C"
entrySelector = "article.article"
titleSelector = "h6.font-weight-bold"
linkSelector = "h6.font-weight-bold a"
contentSelector = "h6.font-weight-bold a"
dateSelector = "p.float-right.mt-2.date"
dateFormat = "yyyy.MM.dd"
imageSelector = "figure.article-image img.d-block.w-100"
waitUntil = "networkidle"

[news_religion]
title = "뉴스타파 ─ 뉴스 ─ 종교"
url = "http://newstapa.org/category/%EC%A2%85%EA%B5%90"
entrySelector = "article.article"
titleSelector = "h6.font-weight-bold"
linkSelector = "h6.font-weight-bold a"
contentSelector = "h6.font-weight-bold a"
dateSelector = "p.float-right.mt-2.date"
dateFormat = "yyyy.MM.dd"
imageSelector = "figure.article-image img.d-block.w-100"
waitUntil = "networkidle"

[news_economy]
title = "뉴스타파 ─ 뉴스 ─ 경제소비자"
url = "http://newstapa.org/category/%EA%B2%BD%EC%A0%9C%EC%86%8C%EB%B9%84%EC%9E%90"
entrySelector = "article.article"
titleSelector = "h6.font-weight-bold"
linkSelector = "h6.font-weight-bold a"
contentSelector = "h6.font-weight-bold a"
dateSelector = "p.float-right.mt-2.date"
dateFormat = "yyyy.MM.dd"
imageSelector = "figure.article-image img.d-block.w-100"
waitUntil = "networkidle"

[news_environment]
title = "뉴스타파 ─ 뉴스 ─ 환경"
url = "http://newstapa.org/category/%ED%99%98%EA%B2%BD"
entrySelector = "article.article"
titleSelector = "h6.font-weight-bold"
linkSelector = "h6.font-weight-bold a"
contentSelector = "h6.font-weight-bold a"
dateSelector = "p.float-right.mt-2.date"
dateFormat = "yyyy.MM.dd"
imageSelector = "figure.article-image img.d-block.w-100"
waitUntil = "networkidle"

[news_laborrights]
title = "뉴스타파 ─ 뉴스 ─ "
url = "http://newstapa.org/category/%EB%85%B8%EB%8F%99%EC%9D%B8%EA%B6%8C"
entrySelector = "article.article"
titleSelector = "h6.font-weight-bold"
linkSelector = "h6.font-weight-bold a"
contentSelector = "h6.font-weight-bold a"
dateSelector = "p.float-right.mt-2.date"
dateFormat = "yyyy.MM.dd"
imageSelector = "figure.article-image img.d-block.w-100"
waitUntil = "networkidle"

[news_publicsafety]
title = "뉴스타파 ─ 뉴스 ─ 공공안전"
url = "http://newstapa.org/category/%EA%B3%B5%EA%B3%B5%EC%95%88%EC%A0%84"
entrySelector = "article.article"
titleSelector = "h6.font-weight-bold"
linkSelector = "h6.font-weight-bold a"
contentSelector = "h6.font-weight-bold a"
dateSelector = "p.float-right.mt-2.date"
dateFormat = "yyyy.MM.dd"
imageSelector = "figure.article-image img.d-block.w-100"
waitUntil = "networkidle"

[news_education]
title = "뉴스타파 ─ 뉴스 ─ 교육"
url = "http://newstapa.org/category/%EA%B5%90%EC%9C%A1"
entrySelector = "article.article"
titleSelector = "h6.font-weight-bold"
linkSelector = "h6.font-weight-bold a"
contentSelector = "h6.font-weight-bold a"
dateSelector = "p.float-right.mt-2.date"
dateFormat = "yyyy.MM.dd"
imageSelector = "figure.article-image img.d-block.w-100"
waitUntil = "networkidle"

[news_history]
title = "뉴스타파 ─ 뉴스 ─ 역사"
url = "http://newstapa.org/category/%EC%97%AD%EC%82%AC"
entrySelector = "article.article"
titleSelector = "h6.font-weight-bold"
linkSelector = "h6.font-weight-bold a"
contentSelector = "h6.font-weight-bold a"
dateSelector = "p.float-right.mt-2.date"
dateFormat = "yyyy.MM.dd"
imageSelector = "figure.article-image img.d-block.w-100"
waitUntil = "networkidle"

[news_welfare]
title = "뉴스타파 ─ 뉴스 ─ 보건복지"
url = "http://newstapa.org/category/%EB%B3%B4%EA%B1%B4%EB%B3%B5%EC%A7%80"
entrySelector = "article.article"
titleSelector = "h6.font-weight-bold"
linkSelector = "h6.font-weight-bold a"
contentSelector = "h6.font-weight-bold a"
dateSelector = "p.float-right.mt-2.date"
dateFormat = "yyyy.MM.dd"
imageSelector = "figure.article-image img.d-block.w-100"
waitUntil = "networkidle"

[news_diplomacy]
title = "뉴스타파 ─ 뉴스 ─ 외교안보"
url = "http://newstapa.org/category/%EC%99%B8%EA%B5%90%EC%95%88%EB%B3%B4"
entrySelector = "article.article"
titleSelector = "h6.font-weight-bold"
linkSelector = "h6.font-weight-bold a"
contentSelector = "h6.font-weight-bold a"
dateSelector = "p.float-right.mt-2.date"
dateFormat = "yyyy.MM.dd"
imageSelector = "figure.article-image img.d-block.w-100"
waitUntil = "networkidle"

[news_international]
title = "뉴스타파 ─ 뉴스 ─ 국제협업"
url = "http://newstapa.org/category/%EA%B5%AD%EC%A0%9C%ED%98%91%EC%97%85"
entrySelector = "article.article"
titleSelector = "h6.font-weight-bold"
linkSelector = "h6.font-weight-bold a"
contentSelector = "h6.font-weight-bold a"
dateSelector = "p.float-right.mt-2.date"
dateFormat = "yyyy.MM.dd"
imageSelector = "figure.article-image img.d-block.w-100"
waitUntil = "networkidle"

[news_media]
title = "뉴스타파 ─ 뉴스 ─ 미디어"
url = "http://newstapa.org/category/%EB%AF%B8%EB%94%94%EC%96%B4"
entrySelector = "article.article"
titleSelector = "h6.font-weight-bold"
linkSelector = "h6.font-weight-bold a"
contentSelector = "h6.font-weight-bold a"
dateSelector = "p.float-right.mt-2.date"
dateFormat = "yyyy.MM.dd"
imageSelector = "figure.article-image img.d-block.w-100"
waitUntil = "networkidle"

[project]
title = "뉴스타파 ─ 프로젝트"
url = "http://newstapa.org/projects/list"
entrySelector = "div.list_section-slider-row-block div div.col-lg-3.col-md-6.columns"
titleSelector = "h6.font-weight-bold"
linkSelector = "article.article a"
contentSelector = "p.float-right.mt-2 span"
dateSelector = "p.float-right.mt-2.date"
dateFormat = "yyyy.MM.dd"
imageSelector = "figure.article-image img.d-block.w-100"
waitUntil = "networkidle"

[data]
title = "뉴스타파 ─ 데이터"
url = "http://newstapa.org/projects/data"
entrySelector = "div.list_section-slider-row-block div div.col-lg-3.col-md-6.columns"
titleSelector = "h6.font-weight-bold"
linkSelector = "article.article a"
contentSelector = "p.float-right.mt-2 span"
dateSelector = "p.float-right.mt-2.date"
dateFormat = "yyyy.MM.dd"
imageSelector = "figure.article-image img.d-block.w-100"
waitUntil = "networkidle"

[change]
title = "뉴스타파 ─ 변화"
url = "https://www.newstapa.org/tags/%EB%B3%80%ED%99%94"
entrySelector = "div.list_section-slider-row-block div div.col-lg-3.col-md-6.columns"
titleSelector = "h6.font-weight-bold"
linkSelector = "article.article figure.article-image a"
contentSelector = "p.float-right.mt-2.date"
dateSelector = "p.float-right.mt-2.date"
dateFormat = "yyyy.MM.dd"
imageSelector = "figure.article-image img.d-block.w-100"
waitUntil = "networkidle"

[participation]
title = "뉴스타파 ─ 참여"
url = "https://www.newstapa.org/tags/%EC%B0%B8%EC%97%AC"
entrySelector = "div.list_section-slider-row-block div div.col-lg-3.col-md-6.columns"
titleSelector = "h6.font-weight-bold"
linkSelector = "article.article figure.article-image a"
contentSelector = "p.float-right.mt-2.date"
dateSelector = "p.float-right.mt-2.date"
dateFormat = "yyyy.MM.dd"
imageSelector = "figure.article-image img.d-block.w-100"
waitUntil = "networkidle"

[kakao]
title = "뉴스타파 ─ 카카오톡 채널"
url = "https://pf.kakao.com/_xkxkxjXl"
entrySelector = "ul.list_news li"
titleSelector = "span.txt_g"
linkSelector = "a.link_item"
waitUntil = "networkidle"
